DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS rooms;
DROP TABLE IF EXISTS tickets;

CREATE TABLE users (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username TEXT UNIQUE NOT NULL,
	email TEXT UNIQUE NOT NULL,
	password TEXT NOT NULL
);

CREATE TABLE rooms (
	userId INTEGER NOT NULL,
	invite TEXT UNIQUE NOT NULL,
	title TEXT NOT NULL,
	filename TEXT NOT NULL,
	FOREIGN KEY (userId) REFERENCES users (id)
);

CREATE TABLE tickets (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username TEXT NOT NULL,
	email TEXT NOT NULL,
	problem TEXT NOT NULL
);
